### PR TITLE
Darker lines

### LINKED ISSUE #71: Make lines slightly darker
During today's meeting Jack requested that we slightly darken the lines on the chart because when he displays it on a projector it is hard to see.  He doesn't want them to be too dark though because he still needs to select them and see that they are selected.

### LINKED ISSUE #101: In Internet Explorer the lines remain highlighted after you move your cursor off
Whenever you scroll over a line in Firefox or Chrome it will highlight it, but when you move off that line it will unhighlight it.  In IE it looks like it never unhighlights after it is initially highlighted.
safety outlier

### PR DESCRIPTION
**Pull request by samussiah**
# Issues
Closes #71 
Closes #101

### CODE REVIEW

**Comment by samussiah** [comment]
hey @pburnsdata , I modularized onResize() so there are a lot of differences.  focus on the new settings in `src/defaultSettings` and the adding and removing of highlighting in `src/onResize/addEventListeners/highlight` and `src/onResize/addEventListeners/clearHighlight`.

**Comment by pburnsdata** [comment]
It's darker! Looks good, only concern is that because points have outlines around them now, they are getting obscured sometimes by points around them. 

image
Maybe sending them to the front with something like this when they are selected would make sense:  

d3.selection.prototype.moveToFront = function() {
      return this.each(function() {
        this.parentNode.appendChild(this);
      });
    };

(from  https://github.com/wbkd/d3-extended)

**Comment by samussiah** [comment]
Good call @pburnsdata , they're at the forefront.

**Comment by tbaraldi** [comment]
Issue #101 has been fixed for IE

**Pull request merged**
